version: "3.8"
services:
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 54320:5432
    volumes:
      - ./db:/var/lib/postgres/data
  logger:
    build:
      dockerfile: Dockerfile
    container_name: api-logger
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
