services:
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 54320:5432
    volumes:
      - ./db:/var/lib/postgres/data
  logger:
    build:
      dockerfile: Dockerfile
    container_name: api-logger
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
  localqueue:
    image: localstack/localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./.bin/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
